package it.polimi.ingsw.view.GUI;

public enum ErrorType {
    WRONG_NICKNAME,
    WRONG_ADDRESS,
    WRONG_PORT,
    WRONG_PORT_ADDRESS,
    EMPTY_NICKNAME,
    NOT_SPACE,
    NOT_REMOVABLE_TILES,
    WRONG_SERVER,
    EIGHT_SAME,
    FOUR_GROUPS,
    INCREASING_HEIGHT,
    THREE_ROW,
    THREE_COLUMNS,
    TWO_COLUMN,
    TWO_ROW,
    SAME_CORNER,
    SAME_DIAGONAL,
    SIX_GROUPS,
    TWO_SQUARES,
    X_SHAPE,
    ONLY_ONE,
    ERROR_OCCURRED,
    EASTER_EGG;

}
